check coverage report fixing step bug

diff --git a/.github/workflows/static-code-analysis.yml b/.github/workflows/static-code-analysis.yml
--- a/.github/workflows/static-code-analysis.yml
+++ b/.github/workflows/static-code-analysis.yml
@@ -35,9 +35,14 @@ jobs:
 
       - name: Check coverage report
         run: |
-          COVERAGE=$(cat __tests__/coverage/lcov.info | grep -E '^C' | awk '{print $2}')
-          if [ "$COVERAGE" -lt 80 ]; then
-            echo "Coverage is less than 80%: $COVERAGE%"
+          if [ -f "__tests__/coverage/lcov.info" ]; then
+            COVERAGE=$(cat __tests__/coverage/lcov.info | grep -E '^C' | awk '{print $2}')
+            if [ -n "$COVERAGE" ] && [ "$COVERAGE" -lt 80 ]; then
+              echo "Coverage is less than 80%: $COVERAGE%"
+              exit 1
+            fi
+          else
+            echo "Coverage report not found."
             exit 1
           fi
       - name: Upload coverage report
